command: 
  - "gunicorn"
  - "server.app.main:app"
  - "--bind"
  - "0.0.0.0:8000"
  - "--worker-class"
  - "uvicorn.workers.UvicornWorker"
  - "--workers"
  - "2"
  - "--access-logfile"
  - "-"
  - "--error-logfile"
  - "-"
env:
  - name: "ENVIRONMENT"
    value: "production"
  - name: "PGDATABASE"
    valueFrom: "lakebase-db"
  - name: "PGHOST"
    valueFrom: "lakebase-db"
  - name: "PGPORT"
    valueFrom: "lakebase-db"
  - name: "PGSSLMODE"
    valueFrom: "lakebase-db"
  - name: "PGUSER"
    valueFrom: "lakebase-db"
  - name: "PGINSTANCE_NAME"
    valueFrom: "lakebase-db"
  - name: "DATABRICKS_HOST"
    valueFrom: "databricks-workspace"
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
  - name: "PREVIEW_DATA_LIMIT"
    value: "15"
  - name: "PORT"
    value: "8000"