command: 
  - "gunicorn"
  - "server.app:app"
  - "-w"
  - "2"
  - "--worker-class"
  - "uvicorn.workers.UvicornWorker"
env:
  - name: "PGDATABASE"
    valueFrom: "lakebase-db"
  - name: "PGHOST"
    valueFrom: "lakebase-db"
  - name: "PGPORT"
    valueFrom: "lakebase-db"
  - name: "PGSSLMODE"
    valueFrom: "lakebase-db"
  - name: "PGUSER"
    valueFrom: "lakebase-db"
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"